#pragma once

#include "UtilityLogit/Logit.h"
#include "UtilityLogit/utility.h"
#include "UtilityLogit/csvUtils.h"

#include "TransportMode.h"

namespace karri::mode_choice {

    constexpr char parametersFileContent[] =

#include "UtilityLogit/autogenerated_includable_parameters"
;

using namespace karri::mode_choice::utility_logit;

// Decides whether a rider accepts an assignment based on the request and the assignment finder response.
// Computes simple utility function with default parameters and applies a logit model.
class UtilityLogitCriterion {

public:

    explicit UtilityLogitCriterion() :
            logit(utility_logit::exampleUtilityFunction,
                  loadParametersFromCSV<TransportMode, ModeParameters>(std::stringstream(parametersFileContent),
                                                                       stringToTransportMode, fromMap)) {}

    TransportMode apply(const std::vector<Alternative<TransportMode>> &entries) const {
        return logit.select(entries);
    }

private:
    const Logit<TransportMode, ModeParameters> logit;

};


} // karri
