#pragma once

#include "UtilityLogit/Logit.h"
#include "UtilityLogit/utility.h"
#include "UtilityLogit/csvUtils.h"
#include "UtilityLogit/types.h"
#include "TransportMode.h"
#include "ModeChoiceInputStats.h"

namespace karri::mode_choice {
    constexpr char parametersFileContent[] =

#include "UtilityLogit/autogenerated_includable_parameters"
        ;

    using namespace karri::mode_choice::utility_logit;

    // Decides whether a rider accepts an assignment based on the request and the assignment finder response.
    // Computes simple utility function with default parameters and applies a logit model.
    class UtilityLogitCriterion {
    public:
        explicit UtilityLogitCriterion(const RouteState &routeState)
            : routeState(routeState), logit(utility_logit::exampleUtilityFunction,
                  options,loadParametersFromCSV<TransportMode,ModeParameters>(std::stringstream(parametersFileContent),
                      stringToTransportMode, fromMap)) {
        }

        void init() {
            entries.clear();
            stats.reset();
        }

        void registerPed(const int walkingTimeTenthsOfSeconds, const RequestState &) {
            KASSERT(walkingTimeTenthsOfSeconds >= 0 && walkingTimeTenthsOfSeconds < INFTY);
            const auto walkingTimeMinutes = tenthsOfSecondsToMinutes(walkingTimeTenthsOfSeconds);
            entries.push_back({TransportMode::Ped, Attributes{walkingTimeMinutes, 0, 0}, true});
            stats.walkTravelTime = walkingTimeMinutes;
        }

        void registerCar(const int travelTimeTenthsOfSeconds) {
            KASSERT(travelTimeTenthsOfSeconds >= 0 && travelTimeTenthsOfSeconds < INFTY);
            const auto drivingTimeMinutes = tenthsOfSecondsToMinutes(travelTimeTenthsOfSeconds);
            entries.push_back({TransportMode::Car, Attributes{drivingTimeMinutes, 0, 0}, true});
            stats.privateCarTravelTime = drivingTimeMinutes;
        }

        void registerPublicTransport(const int travelTimeTenthsOfSeconds, const int waitTimeTenthsOfSeconds,
                                     const int accEgrTimeTenthsOfSeconds) {
            KASSERT(travelTimeTenthsOfSeconds >= 0 && travelTimeTenthsOfSeconds < INFTY);
            KASSERT(waitTimeTenthsOfSeconds >= 0 && waitTimeTenthsOfSeconds < INFTY);
            KASSERT(accEgrTimeTenthsOfSeconds >= 0 && accEgrTimeTenthsOfSeconds < INFTY);
            const auto travelTimeMinutes = tenthsOfSecondsToMinutes(travelTimeTenthsOfSeconds);
            const auto waitTimeMinutes = tenthsOfSecondsToMinutes(waitTimeTenthsOfSeconds);
            const auto accEgrTimeMinutes = tenthsOfSecondsToMinutes(accEgrTimeTenthsOfSeconds);
            entries.push_back({
                TransportMode::PublicTransport, Attributes{travelTimeMinutes, waitTimeMinutes, accEgrTimeMinutes}, true
            });
            stats.ptTravelTime = travelTimeMinutes;
            stats.ptWaitTime = waitTimeMinutes;
            stats.ptAccEgrTime = accEgrTimeMinutes;
        }

        void registerTaxi(const Assignment &assignment, const RequestState &requestState) {
            using namespace time_utils;
            const auto depTimeAtPickup = getActualDepTimeAtPickup(assignment, requestState, routeState);
            const auto initialPickupDetour = calcInitialPickupDetour(assignment, depTimeAtPickup, requestState,
                                                                     routeState);
            const auto dropoffAtExistingStop = isDropoffAtExistingStop(assignment, routeState);
            const auto arrTimeAtDropoff = getArrTimeAtDropoff(depTimeAtPickup, assignment, initialPickupDetour,
                                                              dropoffAtExistingStop, routeState);
            const double taxiTravelTimeMinutes = tenthsOfSecondsToMinutes(arrTimeAtDropoff - depTimeAtPickup);
            const double taxiWaitTimeMinutes = tenthsOfSecondsToMinutes(
                depTimeAtPickup - requestState.originalRequest.requestTime - assignment.pickup.walkingDist);
            const double taxiAccEgrTimeMinutes = tenthsOfSecondsToMinutes(
                assignment.pickup.walkingDist + assignment.dropoff.walkingDist);
            entries.push_back({
                TransportMode::Taxi, Attributes{taxiTravelTimeMinutes, taxiWaitTimeMinutes, taxiAccEgrTimeMinutes}, true
            });
            stats.taxiTravelTime = taxiTravelTimeMinutes;
            stats.taxiWaitTime = taxiWaitTimeMinutes;
            stats.taxiAccEgrTime = taxiAccEgrTimeMinutes;
        }

        // Executes mode choice with previously registered modes.
        TransportMode apply() const {
            // std::vector<Alternative<TransportMode> > entries = {
            //     {TransportMode::Car, Attributes{input.privateCarTravelTime, 0, 0}, input.isPrivateCarValid()},
            //     {TransportMode::Ped, Attributes{input.walkTravelTime, 0, 0}, input.isWalkValid()},
            //     {
            //         TransportMode::Taxi, Attributes{input.taxiTravelTime, input.taxiWaitTime, input.taxiAccEgrTime},
            //         input.isTaxiValid()
            //     },
            //     {
            //         TransportMode::PublicTransport,
            //         Attributes{input.ptTravelTime, input.ptWaitTime, input.ptAccEgrTime}, input.isPublicTransportValid()
            //     }
            // };
            return logit.select(entries);
        }

        const ModeChoiceInputStats &getStats() const {
            return stats;
        }

    private:
        static const std::vector<TransportMode> options;

        const RouteState &routeState;
        const Logit<TransportMode, ModeParameters> logit;

        std::vector<Alternative<TransportMode> > entries;
        ModeChoiceInputStats stats;

        static constexpr double tenthsOfSecondsToMinutes(const int timeInTenthsOfSeconds) {
            return static_cast<double>(timeInTenthsOfSeconds) / 600.0;
        }
    };

    // out of line definition of static members
    const std::vector<TransportMode> UtilityLogitCriterion::options = {
        TransportMode::Car,
        TransportMode::Ped,
        TransportMode::Taxi,
        TransportMode::PublicTransport
    };
} // karri
